window.addEventListener('pageshow',(event)=>{if(event.persisted){document.body.classList.remove('page-exit');document.body.classList.add('page-loaded')}
const pembinaHome=document.getElementById('pembina-home');if(pembinaHome&&typeof DATA_PENGURUS!=='undefined'){const pembinaData=DATA_PENGURUS.inti&&DATA_PENGURUS.inti.length>0?DATA_PENGURUS.inti[0]:null;if(pembinaData){document.getElementById('home-pembina-nama').textContent=pembinaData.nama||'Nama Pembina';if(pembinaData.motto){document.getElementById('home-pembina-motto').textContent='"'+pembinaData.motto+'"'}
const fotoFile=pembinaData.foto||"left-man.webp";let fotoPath=fotoFile;if(!fotoFile.includes("/")){if(fotoFile==="left-man.webp"||fotoFile==="right-man.webp"){fotoPath=`./global/assets/assets global/${fotoFile}`}else{fotoPath=`./global/assets/assets struktur/inti/${fotoFile}`}}
document.getElementById('home-pembina-img').src=fotoPath}}
if(typeof DATA_PENGURUS!=='undefined'&&document.getElementById('home-ketua-img')){const ketuaData=DATA_PENGURUS.inti.find(p=>p.jabatan==="Ketua OSIS");if(ketuaData){const nameEl=document.getElementById('home-ketua-nama');if(nameEl&&ketuaData.nama)nameEl.textContent=ketuaData.nama;const pesanEl=document.getElementById('home-ketua-pesan');if(pesanEl&&ketuaData.motto){pesanEl.textContent='"'+ketuaData.motto+'"'}
const fotoFile=ketuaData.foto||"left-man.webp";let fotoPath=fotoFile;if(!fotoFile.includes("/")){if(fotoFile==="right-man.webp"||fotoFile==="left-man.webp"||fotoFile==="Logo Osis.webp"){fotoPath="./global/assets/assets global/"+fotoFile}else{fotoPath="./global/assets/assets struktur/inti/"+fotoFile}}
document.getElementById('home-ketua-img').src=fotoPath}}
const beritaHomeGrid=document.getElementById('berita-home-grid');if(beritaHomeGrid){fetch('./kegiatan/db/beritasekolah-data.json').then(response=>response.json()).then(data=>{const latest=data.slice(0,3);let html='';latest.forEach((item,index)=>{const shortCaption=item.caption.length>100?item.caption.substring(0,100)+'...':item.caption;let embedUrl=item.link;if(embedUrl&&!embedUrl.includes('/embed')){embedUrl=embedUrl.endsWith('/')?embedUrl+'embed/':embedUrl+'/embed/'}
html+=`
                    <div class="news-card reveal">
                        <div class="news-img-wrapper">
                            <iframe src="${embedUrl}" allowtransparency="true" allow="encrypted-media" scrolling="no" frameborder="0" loading="lazy" style="width: 100%; height: 100%; position: absolute; top: 0; left: 0;"></iframe>
                        </div>
                        <div class="news-content">
                            <div class="news-date">${item.date}</div>
                            <h3 class="news-title">${item.title}</h3>
                            <p class="news-excerpt">${shortCaption}</p>
                            <a href="${item.link}" target="_blank" class="news-read-more">Baca Selengkapnya <span>&rarr;</span></a>
                        </div>
                    </div>
                    `});beritaHomeGrid.innerHTML=html;setTimeout(()=>{document.querySelectorAll('.news-card.reveal').forEach(el=>{if(typeof revealObserver!=='undefined'){revealObserver.observe(el)}else{el.classList.add('active')}})},100)}).catch(err=>{console.error('Error loading news:',err);beritaHomeGrid.innerHTML='<p style="text-align:center; color: var(--gray-light);">Gagal memuat berita terbaru.</p>'})}});document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{document.body.classList.add('page-loaded')},50);const footerPlaceholder=document.getElementById('footer-placeholder');if(footerPlaceholder){const scripts=document.getElementsByTagName('script');let basePath='./';for(let s of scripts){const src=s.getAttribute('src');if(src&&src.includes('global/js/global.js')){basePath=src.replace('global/js/global.js','');break}}
if(basePath==='')basePath='./';const headerPlaceholder=document.getElementById('header-placeholder');if(headerPlaceholder){const headerUrl=basePath+'layout/header.html';fetch(headerUrl+'?v='+new Date().getTime()).then(response=>{if(!response.ok)throw new Error('Header fetch failed');return response.text()}).then(html=>{const resolvedHtml=html.replace(/\{\{BASE_PATH\}\}/g,basePath);headerPlaceholder.innerHTML=resolvedHtml;const currentPath=window.location.pathname;const links=headerPlaceholder.querySelectorAll('.nav-links a');links.forEach(link=>{const href=link.getAttribute('href');if(href&&href!=='#'&&currentPath.includes(href.replace(basePath,''))){links.forEach(l=>l.classList.remove('active'));link.classList.add('active')}});const navbar=document.querySelector('.navbar');if(navbar){const handleScroll=()=>{if(window.scrollY>20){navbar.classList.add('navbar-scrolled')}else{navbar.classList.remove('navbar-scrolled')}};handleScroll();window.addEventListener('scroll',handleScroll,{passive:!0})}
const mobileBtn=headerPlaceholder.querySelector('.mobile-menu-btn');const navContainer=headerPlaceholder.querySelector('.nav-links');if(mobileBtn&&navContainer){mobileBtn.addEventListener('click',(e)=>{e.stopPropagation();mobileBtn.classList.toggle('active');navContainer.classList.toggle('active')});document.addEventListener('click',(e)=>{if(!navContainer.contains(e.target)&&!mobileBtn.contains(e.target)&&navContainer.classList.contains('active')){mobileBtn.classList.remove('active');navContainer.classList.remove('active')}});const dropdowns=navContainer.querySelectorAll('.dropdown > a');dropdowns.forEach(drop=>{drop.addEventListener('click',(e)=>{if(window.innerWidth<=992){e.preventDefault();e.stopPropagation();const parentLi=drop.parentElement;parentLi.classList.toggle('active')}})})}}).catch(error=>console.error('Error loading header:',error))}
const footerUrl=basePath+'layout/footer.html';fetch(footerUrl+'?v='+new Date().getTime()).then(response=>{if(!response.ok)throw new Error('Footer fetch failed');return response.text()}).then(html=>{const resolvedHtml=html.replace(/\{\{BASE_PATH\}\}/g,basePath);footerPlaceholder.innerHTML=resolvedHtml;const newRevealElements=footerPlaceholder.querySelectorAll('.reveal, .reveal-stagger');newRevealElements.forEach(el=>revealObserver.observe(el))}).catch(error=>console.error('Error loading footer:',error))}
const links=document.querySelectorAll('a[href]');links.forEach(link=>{link.addEventListener('click',function(e){const target=this.getAttribute('href');if(target.startsWith('#')||target.startsWith('mailto:')||this.getAttribute('target')==='_blank'||target===''){return}
e.preventDefault();document.body.classList.remove('page-loaded');document.body.classList.add('page-exit');setTimeout(()=>{window.location.href=target},500)})});const tabContainers=document.querySelectorAll('.tabs-container');tabContainers.forEach(container=>{const buttons=container.querySelectorAll('.tab-btn');const contents=container.querySelectorAll('.tab-content');buttons.forEach((btn,index)=>{btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));contents.forEach(c=>c.classList.remove('active'));btn.classList.add('active');if(contents[index]){contents[index].classList.add('active')}})})});const revealCallback=(entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('active')}})};const revealObserver=new IntersectionObserver(revealCallback,{threshold:0.15});const revealElements=document.querySelectorAll('.reveal, .reveal-stagger');revealElements.forEach(el=>revealObserver.observe(el))})
